---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге после добавления товара в корзину
  - Находясь на странице корзины, пользователь должен иметь возможность удалить товар из корзины, продолжить выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт магазина должен представлять из себя SPA-приложение, работающее без перезагрузки страницы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен выводить название товара, рейтинг, цену со скидкой и цену без нее на странице товара и в каталоге
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Корзина сайта должна храниться в сессии браузера
implicit:
  - Важно, чтобы мобильная версия сайта не уступала десктопной в удобстве использования
  - Сайт нужно протестировать на правильное распределение по версиям(мобильной и десктопной) сайта в зависимости от устройства пользователя
  - Нужно проверить что при основных действиях пользователя(переход в корзину, на другую страницу, оформление заказа, применение фильтра) не будет происходить перезагрузка страницы
  - При переходе на другую страницу с товарами должен показываться значок загрузки
  - Пользователь не должен иметь возможность просмотра чужих заказов путём введения URL страницы соответствующего заказа в браузере либо каким-то другим обходным путём
  - Поиск по ключевому слову не должен выдавать ни одного лишнего результата, но при этом выдавать абсолютно все результаты по введённому ключевому слову
