---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Важно, чтобы мобильная версия сайта не уступала десктопной в удобстве использования
  - Сайт нужно протестировать на правильное распределение по версиям(мобильной и десктопной) сайта в зависимости от устройства пользователя
  - Нужно проверить что при основных действиях пользователя(переход в корзину, на другую страницу, оформление заказа, применение фильтра) не будет происходить перезагрузка страницы
  - При переходе на другую страницу с товарами должен показываться значок загрузки
  - При регистрации пользователь не должен иметь возможность задать пароль, не соответствующий требованиям безопасности(не менее 6 символов, минимум одна цифра, минимум один специальный символ)
  - Пользователь не должен иметь возможность просмотра чужих заказов путём введения URL страницы соответствующего заказа в браузере либо каким-то другим обходным путём
  - Поиск по ключевому слову не должен выдавать ни одного лишнего результата, но при этом выдавать абсолютно все результаты по введённому ключевому слову
